version: '3'

services:
  database:
    image: postgres
    container_name: database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=henrique
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=instant-db